# Generated by Django 3.0.6 on 2020-07-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_telepon', models.CharField(max_length=50)),
                ('terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_nota', models.CharField(max_length=255)),
                ('status_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harga', models.FloatField(blank=True, null=True)),
                ('provinsi_asal', models.CharField(default='11', max_length=255)),
                ('kota_asal', models.CharField(default='42', max_length=255)),
                ('kecamatan_asal', models.CharField(default='611', max_length=255)),
                ('provinsi_tujuan', models.CharField(blank=True, max_length=255, null=True)),
                ('kota_tujuan', models.CharField(blank=True, max_length=255, null=True)),
                ('kecamatan_tujuan', models.CharField(blank=True, max_length=255, null=True)),
                ('jasa_ongkir', models.CharField(default='jne', max_length=50)),
                ('harga_ongkir', models.FloatField(default=0)),
                ('total_harga', models.FloatField(default=0)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti/')),
                ('status_bayar', models.CharField(choices=[('SUDAH', 'sudah'), ('BELUM', 'belum')], default='BELUM', max_length=50)),
                ('alamat', models.TextField()),
                ('resi', models.CharField(blank=True, default='Menunggu nomor resi', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('harga', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='documents/')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bukti_pembayaran', models.ImageField(upload_to='bukti/')),
                ('kode_nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_harga', models.FloatField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product')),
            ],
        ),
    ]
