# Generated by Django 3.0.6 on 2020-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_bayar',
            field=models.CharField(choices=[('SUDAH', 'sudah'), ('BELUM', 'belum')], default='BELUM', max_length=50),
        ),
    ]
