# Generated by Django 3.0.6 on 2020-07-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_status_bayar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='resi',
            field=models.CharField(blank=True, default='Menunggu nomor resi', max_length=255, null=True),
        ),
    ]
