# Generated by Django 3.0.6 on 2020-06-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200614_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kota_asal',
            field=models.CharField(default='42', max_length=255),
        ),
    ]
