# Generated by Django 3.0.6 on 2020-06-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_kota_asal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='provisi_tujuan',
            new_name='provinsi_tujuan',
        ),
    ]
