# Generated by Django 3.0.6 on 2020-06-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200614_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kecamatan_tujuan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='kota_tujuan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='provinsi_tujuan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
