# Generated by Django 3.0.6 on 2020-06-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200617_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_harga',
            field=models.FloatField(default=0),
        ),
    ]
