# Generated by Django 3.0.6 on 2020-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_total_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_harga',
            field=models.FloatField(default=0),
        ),
    ]
